# Numpy 
Numpy is a general-purpose array-processing package. It provides a high performance multidimensional array object and tools for working with these arrays. It is the fundamental package for scientific computing with python.

# What is an Array?
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While Python lists can contain values corresponding to different data types, arrays in Python can only contain values

In [2]:
# intially lets import Numpy
import numpy as np

In [3]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.shape

(5,)

In [24]:
# Multidimensional array
my_list1=[1,2,3,4,5,6]
my_list2=[2,3,4,5,6,7]
my_list3=[4,5,2,4,5,6]

In [25]:
arr=np.array([my_list1,my_list2,my_list3])

In [11]:
arr

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7],
       [4, 5, 2, 4, 5, 6]])

In [12]:
arr.shape

(3, 6)

In [15]:
arr.reshape(6,3)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [5, 6, 7],
       [4, 5, 2],
       [4, 5, 6]])

In [16]:
arr.shape

(3, 6)

In [17]:
arr.reshape(1,18)

array([[1, 2, 3, 4, 5, 6, 2, 3, 4, 5, 6, 7, 4, 5, 2, 4, 5, 6]])

In [18]:
# as check the shape of the array
arr.shape

(3, 6)

# Indexing

In [20]:
# Accessing the array element
arr=np.array([1,2,3,4,5,6,7,8,9,10])

In [21]:
arr[4]

5

In [26]:
arr

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7],
       [4, 5, 2, 4, 5, 6]])

In [38]:
arr[:,:]

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7],
       [4, 5, 2, 4, 5, 6]])

In [33]:
arr[0:2,:]

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7]])

In [29]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [39]:
arr[1:,3:]

array([[5, 6, 7],
       [4, 5, 6]])

In [67]:
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[9,7,6,8,9]

In [68]:
arr=np.array([list1,list2,list3])

In [69]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [49]:
arr[1:2,2:]

array([[4, 5, 6]])

In [64]:
arr[2:,3:4]

array([[8]])

In [60]:
arr[0:1,2:]

array([[3, 4, 5]])

In [82]:
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[9,7,6,8,9]

In [83]:
arr=np.array([list1,list2,list3])

In [84]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [87]:
arr=np.arange(0,10)

In [88]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
arr=np.arange(0,10,step=2)

In [90]:
arr

array([0, 2, 4, 6, 8])

In [91]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [97]:
arr=np.arange(0,10)

In [98]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
## copy
arr[3:]=100

In [100]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [101]:
#copy() function and broadcasting
arr1=arr

In [102]:
arr1[3:]=500
print(arr1)

[  0   1   2 500 500 500 500 500 500 500]


In [103]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [104]:
arr1=arr.copy()

In [107]:
print(arr)
arr1[3:]=1000
print(arr1)

[  0   1   2 500 500 500 500 500 500 500]
[   0    1    2 1000 1000 1000 1000 1000 1000 1000]


In [108]:
# some conditions very useful in Exploratory Data Analysis
val=2
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [109]:
val=2
arr>2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [110]:
val=2
arr*val

array([   0,    2,    4, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [111]:
arr/val

array([  0. ,   0.5,   1. , 250. , 250. , 250. , 250. , 250. , 250. ,
       250. ])

In [112]:
arr%val

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [113]:
arr[arr>2]

array([500, 500, 500, 500, 500, 500, 500])

In [114]:
arr[arr<2]

array([0, 1])

In [115]:
## create arrays and reshape
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [116]:
arr1=np.arange(10,20).reshape(2,5)

In [125]:
arr1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [122]:
aar2=np.arange(20,30).reshape(2,5)

In [126]:
aar2

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [129]:
arr1*aar2

array([[200, 231, 264, 299, 336],
       [375, 416, 459, 504, 551]])

In [135]:
np.ones((4), dtype=int)

array([1, 1, 1, 1])

In [136]:
np.ones((2,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [137]:
## randon distribution
np.random.rand(2,2)

array([[0.76639343, 0.10903862],
       [0.19980158, 0.23550556]])

In [138]:
np.random.rand(3,3)

array([[0.25927984, 0.61168348, 0.48602107],
       [0.36039105, 0.77217841, 0.70744896],
       [0.97072142, 0.07466253, 0.29990654]])

In [139]:
np.random.rand(3,4)

array([[0.4707874 , 0.91150171, 0.03629487, 0.28761784],
       [0.7746015 , 0.97259046, 0.33951355, 0.41061205],
       [0.25945846, 0.86843373, 0.64990323, 0.32841182]])

In [142]:
arr_ex=np.random.randn(4,4)

In [143]:
arr_ex

array([[ 1.2766587 ,  1.13946092, -0.57772914,  0.18949891],
       [ 0.04114723, -0.11467773,  0.76597324, -0.11378098],
       [-2.25349638,  1.48546777, -1.0850251 , -1.54981172],
       [ 1.39220567,  0.30992952,  0.34553427, -1.56444001]])

In [153]:
np.random.randint(0,1000,8)

array([390, 593, 897, 330, 823, 744, 488,  77])

In [154]:
np.random.random_sample((1,5))

array([[0.16334694, 0.7346445 , 0.55991752, 0.45395397, 0.43639445]])